version: '3'

tasks:
  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  run:
    desc: Run the application
    cmds:
      - go run .

  build:
    desc: Build the application
    cmds:
      - go build -o bin/app

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/

  docker-build:
    desc: Build Docker image
    cmds:
      - docker build -t snippetbox:latest .

  docker-run:
    desc: Run Docker container
    cmds:
      - docker run -p 4000:4000 snippetbox:latest

  docker-stop:
    desc: Stop Docker container
    cmds:
      - docker stop $(docker ps -q --filter ancestor=snippetbox:latest)